name: daakesh
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  cupertino_icons: ^1.0.2
  #State management
  flutter_bloc: ^8.1.3
  #Dependency injection
  injectable: ^2.3.2
  get_it: ^7.6.7
  #http
  http: ^1.1.0
  #Comparing objects
  equatable: ^2.0.5
  #Json theme
  json_theme: ^6.3.0
  #Path
  path: ^1.8.3
  #Connection check
  connectivity_plus: ^5.0.2
  #Mockicto
  mockito: ^5.4.4
  #functional
  dartz: ^0.10.1
  #Tooles_Packages
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.1
  lint: ^2.2.0
  #Widgets
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.24
  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.14









dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  test: ^1.24.3
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.5
  injectable_generator: ^2.4.1

flutter_gen:
  colors:
    inputs:
      - assets/colors/colors.xml

  integrations:
    flutter_svg: true


flutter:
  generate: true
  uses-material-design: true



  assets:
     - assets/png/
     - assets/svg/

  # example:
  fonts:
     - family: Apercu-Bold
       fonts:
         - asset: assets/fonts/apercu/apercu_bold_pro.otf

     - family: Apercu-Medium
       fonts:
         - asset: assets/fonts/apercu/apercu_medium_pro.otf

     - family: Apercu-Regular
       fonts:
         - asset: assets/fonts/apercu/apercu_regular_pro.otf

     - family: Sf-Pro-Display-Regular
       fonts:
         - asset: assets/fonts/sf_pro_display/sf_pro_display_regular.otf

     - family: Segoe-UI-Semi-Bold
       fonts:
         - asset: assets/fonts/segoe_ui/segoe_ui_semi_bold.ttf



