// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpDXfVlGG-OW-6oogrEdVXCyq_LxeY2aQ',
    appId: '1:311956579675:android:4b03a205a92c6bc8dc267e',
    messagingSenderId: '311956579675',
    projectId: 'daakesh-af3a0',
    storageBucket: 'daakesh-af3a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7DzV798f8gc-M48lDJS9ft2oGu8uZpc',
    appId: '1:311956579675:ios:f04d0a7e63535fc7dc267e',
    messagingSenderId: '311956579675',
    projectId: 'daakesh-af3a0',
    storageBucket: 'daakesh-af3a0.appspot.com',
    androidClientId: '311956579675-i4j6plvkcanicnitbuhk0sk4jr4708fl.apps.googleusercontent.com',
    iosClientId: '311956579675-arfufcsof1suvthfqpg61q6rueanmg9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.daakesh',
  );
}
